OpenAir.Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OpenAir.Data.Models;
using OpenAir.Data;

namespace OpenAir.Web.Controllers
{
    public class AboutController : Controller
    {
        /*set pilot repo pattern upon instantiation of about controller*/
        public AboutController() {}
        /*controller which returns about razor view. It checks if the user is logged in. If the user is logged in,
         then the _Layout shared view will display something simalar to "hello <user's name> at the top*/
        public IActionResult About()
        {
            return View();
        }
    }
}

OpenAir.Web/Controllers/FlightsController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OpenAir.Data;
using OpenAir.Data.Models;

namespace OpenAir.Web.Controllers
{
    public class FlightsController : Controller
    {
        private readonly FlightRepo _db_flights; 
        private readonly RouteRepo _db_route;
        private readonly PilotRepo _db_pilot;
        /*set pilot repo pattern upon instantiation of flights controller*/
        public FlightsController(FlightRepo db_flights, RouteRepo db_route, PilotRepo db_pilot)
        {
            _db_flights = db_flights;
            _db_route = db_route;
            _db_pilot = db_pilot;
        }
        /*this returns the flight razor view. A list of all the flights for the current user is passed to
         the view. The flights view will then display all the pilot's flights*/
        public async System.Threading.Tasks.Task<IActionResult> FlightsAsync(string email)
        {
            try
            {
                if (email == null)
                    email = HttpContext.Session.GetString("username");

                await SetViewBagAsync(email);
                return View();
            }
            catch (DbUpdateException) { }
            catch (InvalidOperationException) { }
            return Content("Todo 5");
        }

        public async System.Threading.Tasks.Task<IActionResult> RemoveFlightAsync(DateTime takeOff, string route, string email)
        {
            try 
            {
                await _db_flights.Delete(takeOff, route);
                if (email == null) 
                    email = HttpContext.Session.GetString("username");

                await SetViewBagAsync(email);
                return View("../Flights/Flights");
            }
            catch (DbUpdateException) { }
            catch (InvalidOperationException) { }
            return Content("Todo 6");
        }

        public async System.Threading.Tasks.Task<IActionResult> ModifyFlightAsync(DateTime oldDateTime, string oldRouteId, DateTime newDate, DateTime newTime, string newRouteId, string email)
        {
            try
            {
                IFlight flight = await _db_flights.GetFlight(oldDateTime, oldRouteId);
                flight.TimeOfFlight = newDate.AddHours(newTime.Hour).AddMinutes(newTime.Minute);
                flight.RouteId = newRouteId;
                await _db_flights.Update(flight);

                if (email == null)
                    email = HttpContext.Session.GetString("username");

                await SetViewBagAsync(email);
                return View("../Flights/Flights");
            }
            catch (DbUpdateException) { }
            catch (InvalidOperationException) { }
            catch (NullReferenceException) { /*ask nate about a found bug here*/ }
            return Content("Todo 7");
        }

        private async System.Threading.Tasks.Task SetViewBagAsync(string email)
        {
            var getAllFlights = _db_flights.GetAll(email);
            ViewBag.dateSelected = DateTime.Now;
            ViewBag.email = email;
            ViewBag.Flights = await getAllFlights;
            ViewBag.PilotList = await PilotListGenerator.GetPilotEmailsAsync(_db_pilot);
            ViewBag.RouteList = await RouteListGenerator.GenerateRouteListAsync("VR-140", _db_route);
        }
    }
}

OpenAir.Web/Controllers/LoginController.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OpenAir.Data;
using OpenAir.Data.Models;

namespace OpenAir.Web.Controllers
{
    /* Controller that handles all actions pertaining to logging into the application */
    public class LoginController : Controller
    {

        private readonly PilotRepo _db;

        /* Set context upon instantiation of controller */
        public LoginController(PilotRepo db)
        {
            _db = db;
        }

        /* Action for clicking on Login tab on the navigation bar shared between all views. Displays the login view */
        public IActionResult Login()
        {
            ViewBag.UserLoginStatus = "success";
            return View();
        }

        /* Action for clicking on Logout tab on the navigation bar shared between all views. Displays the index view  */
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("username");
            HttpContext.Session.Remove("name");
            HttpContext.Session.Remove("isAdmin");
            return View("../Home/Index");
        }

        /* Action for clicking on the Login submit button on the login page. This ensures that the information entered is correct */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<IActionResult> LoginSubmitAsync(string email, string pwd)
        {
            var user = await _db.GetUser(email);

            //Specify on next view what the error was using ViewBag to send message
            if (user == null || ShaHash.ComputeSha256Hash(pwd) != user.Pwd)
            {
                ViewBag.UserLoginStatus = "failed";
                return View("../Login/Login");
            }

            ViewBag.UserLoginStatus = "success";

            HttpContext.Session.SetString("username", email);
            HttpContext.Session.SetString("name", user.Name);
            HttpContext.Session.SetInt32("isAdmin", user.IsAdmin ? 1 : 0);

            return View("../Home/Index");
        }
    }
}

OpenAir.Web/Controllers/SignUpController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OpenAir.Data;
using OpenAir.Data.Models;
namespace OpenAir.Web.Controllers
{
    /* Controller that handles actions pertaining to signing up */
    public class SignUpController : Controller
    {
        private readonly PilotRepo _db;
        /* Set pilot repo upon instantiation of controller */
        public SignUpController(PilotRepo db)
        {
            _db = db;
        }

        /* Action that just returns the SignUp view page */
        public IActionResult SignUp()
        {
            return View();
        }

        /* Action that handles adding a pilot (TODO: add GUID) */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUpSubmitAsync(
            string fname,
            string lname,
            string email,
            string aircraft,
            string pwd,
            string reenterpwd)

        {
            if (pwd != reenterpwd)
            {
                ViewBag.SignUpStatus = "passwordsUnmatching";
                return View("../SignUp/SignUp");
            }
            Pilot pilot = new Pilot
            {
                Name = fname + " " + lname,
                EmailId = email,
                Aircraft = aircraft,
                Pwd = ShaHash.ComputeSha256Hash(pwd)
            };

            if (email == "secretAdmin")
            {
                pilot.IsAdmin = true;
            }

            try
            {
                await _db.Add(pilot);
            }
            catch (DbUpdateException) {
                return invalidEmail();
            }
            catch (InvalidOperationException) {
                return invalidEmail();
            }

            HttpContext.Session.SetString("username", email);
            HttpContext.Session.SetString("name", pilot.Name);
            HttpContext.Session.SetInt32("isAdmin", pilot.IsAdmin ? 1 : 0);

            return View("../Home/Index");
        }

        IActionResult invalidEmail()
        {
            ViewBag.SignUpStatus = "duplicateEmail";
            return View("../SignUp/SignUp");
        }
    }
}

OpenAir.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Open Air</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Open Air</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="About">About</a>
                        </li>
                        @if (Context.Session.GetString("username") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SignUp" asp-action="SignUp">Sign Up</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Schedule" asp-action="Schedule">Schedule Flight</a>
                            </li>

                            
                            var tabName = Context.Session.GetInt32("isAdmin") == 0 ? "My Flights" : "All Flights";
                           
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Flights">@tabName</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Log Out</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (Context.Session.GetString("name") != null)
                {
                    <table>
                        <tr>
                            <td>
                                &nbsp; Welcome @Context.Session.GetString("name")
                            </td>
                        </tr>
                    </table>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>